#version: '3.1'  # docker-compose -f docker-compose-prod.yml up -d
#1. docker-compose -f docker-compose-prod.yml build --no-cache
#2. docker-compose -f docker-compose-prod.yml up -d --remove-orphans


services:

  product:
    build:
      context: .
      dockerfile: ./apps/product/Dockerfile
      target: development
    command: pnpm run start:dev product
    depends_on:
      postgres_product:
        condition: service_healthy
    env_file:
      - ./apps/product/.env
    ports:
      - '3002:3002'  
    volumes:
      #- ./apps/product:/usr/src/app/apps/product
      - .:/usr/src/app
      - /usr/src/app/node_modules


  postgres_product:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '6002:5432'
    volumes:
      - ./postgres/product:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s


      
    