# docker-compose -f docker-compose.prod.yml build --no-cache
# docker-compose -f docker-compose.prod.yml up --build

services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    image: DockerHubID/fc-nestjs-gateway:latest
    env_file:
      - ./apps/gateway/.env.production
    ports:
      - "3000:3000"

  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
    image: DockerHubID/fc-nestjs-user:latest
    env_file:
      - ./apps/user/.env.production

  product:
    build:
      context: .
      dockerfile: ./apps/product/Dockerfile
    image: DockerHubID/fc-nestjs-product:latest
    env_file:
      - ./apps/product/.env.production

  order:
    build:
      context: .
      dockerfile: ./apps/order/Dockerfile
    image: DockerHubID/fc-nestjs-order:latest
    env_file:
      - ./apps/order/.env.production

  payment:
    build:
      context: .
      dockerfile: ./apps/payment/Dockerfile
    image: DockerHubID/fc-nestjs-payment:latest
    env_file:
      - ./apps/payment/.env.production

  notification:
    build:
      context: .
      dockerfile: ./apps/notification/Dockerfile
    image: DockerHubID/fc-nestjs-notification:latest
    env_file:
      - ./apps/notification/.env.production
