#version: '3.1'  # docker-compose -f docker-compose-user.yml up -d
#1. docker-compose -f docker-compose-user.yml build --no-cache
#2. docker-compose -f docker-compose-user.yml -p nestjs-delivery-user up -d --remove-orphans


#멀티로그  : docker-compose -f docker-compose-user.yml -f docker-compose-order.yml logs -f user order


services:
  user:
    environment:
      - TCP_PORT=4001
      - HTTP_PORT=3001
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      target: development
    command: pnpm run start:dev user
    depends_on:
      postgres_user:
        condition: service_healthy
    env_file:
      - ./apps/user/.env
    ports:
      - '3001:3001' # HTTP만 호스트에 노출
    volumes:
      - ./apps/user:/usr/src/app/apps/user
      - /usr/src/app/node_modules

  postgres_user:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '6001:5432'
    volumes:
      - ./postgres/user:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

      
    