#version: '3.1'  # docker-compose -f docker-compose-notification.yml up -d
#1. docker-compose -f docker-compose-notification.yml build --no-cache
#2. docker-compose -f docker-compose-notification.yml up -d --remove-orphans
#실시간 로그 확인 docker-compose -f docker-compose-notification.yml logs -f notification



services:

  notification:
    build:
      context: .
      dockerfile: ./apps/notification/Dockerfile
      target: development
    command: pnpm run start:dev notification
    depends_on:
      mongo_notification:
        condition: service_healthy
    env_file:
      - ./apps/notification/.env
    ports:
      - '3005:3005'  
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules


  mongo_notification:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - '6005:27017'
    volumes:
      - ./mongo/notification:/data/lib
    command: mongod --quiet --logpath /dev/null
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s